services:
  - type: web
    name: laravel-docker
    env: docker
    plan: free
    image: fatoumatbinetousylla/appcompt:latest
    envVars:
      - key: APP_KEY
        value: base64:zdGGyAF9ualOupCCpG9qvTt+duJaJjj8DC7T5pZP6ew=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://fatoumata-apisylla-1.onrender.com/
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: pgsql
          property: host
      - key: DB_PORT
        value: 5433
      - key: DB_DATABASE
        fromDatabase:
          name: pgsql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: pgsql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pgsql
          property: password
      - key: L5_SWAGGER_BASE_PATH
        value: https://fatoumata-apisylla-1.onrender.com/
      - key: L5_SWAGGER_USE_ABSOLUTE_PATH
        value: true
      - key: L5_SWAGGER_CONST_HOST
        value: https://fatoumata-apisylla-1.onrender.com/
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.mailtrap.io # Exemple, à remplacer par le vrai hôte SMTP
      - key: MAIL_PORT
        value: 2525 # Exemple, à remplacer par le vrai port SMTP
      - key: MAIL_USERNAME
        value: your_mailtrap_username # Exemple, à remplacer par le vrai nom d'utilisateur SMTP
      - key: MAIL_PASSWORD
        value: your_mailtrap_password # Exemple, à remplacer par le vrai mot de passe SMTP
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: no-reply@example.com
      - key: MAIL_FROM_NAME
        value: "API Comptes"
      # - key: TWILIO_SID
      #   value: your_twilio_sid # À remplacer par votre SID Twilio
      # - key: TWILIO_TOKEN
      #   value: your_twilio_token # À remplacer par votre Token Twilio
>>>>>>> c72b9289545d203b5c46a4a7ff487701a6f244ef
      - key: TWILIO_FROM



    

databases:
  - name: pgsql
    plan: free
